name = "Framed2TM"
version = "0.1.0"
license = "license"
author = "lidaltonlima"
maintainer = "lidaltonlima@gmail.com"
copyright = "Copyright 2026, lidaltonlima"

[library]
source-dir = "src"

[preprocess]
[preprocess.cpp]
suffixes = ["F90"]

[[executable]]
name = "main"
source-dir = "app"
main = "main.f90"

[[test]]
name = "check"
source-dir = "test"
main = "StructureTest.f90"

[fortran]
source-form = "default"
implicit-typing = true
implicit-external = true
